#!/usr/bin/env python3
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from dotenv import load_dotenv
import os

load_dotenv()

PASS = os.getenv("EMAIL_PASS")
if not PASS:
    raise ValueError("EMAIL_PASS not found in .env file!")

USER = os.getenv("EMAIL_USER")
if not USER:
    raise ValueError("EMAIL_USER not found in .env file!")

# Config with defaults
SMTP_SERVER = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT = int(os.getenv("SMTP_PORT", "465"))
FROM = os.getenv("EMAIL_FROM", USER)  # Default to USER if not set
# Handle TO list - can be comma-separated in env var
TO_ENV = os.getenv("EMAIL_TO", "yzc526@163.com")
TO = [email.strip() for email in TO_ENV.split(",")]


# Print configuration (using correct methods)
print(f"✅ Email configured:")
print(f"  • USER: {USER}")
print(f"  • PASS: {'*' * len(PASS)}")  # Mask password for security
print(f"  • TO: {', '.join(TO)}")       # join() works here because TO is a list
print(f"  • SMTP: {SMTP_SERVER}:{SMTP_PORT}")

# Build message
msg = MIMEMultipart('alternative')
msg['Subject'] = "[Test] Skill Monitor Email Test"
msg['From'] = FROM
msg['To'] = ', '.join(TO)  # join() works here because TO is a list

text = "This is a test email from OpenClaw Skill Monitor.\nIf you see this, email works! ✅"
html = """
<html><body>
<h2>🔍 OpenClaw Skill Monitor</h2>
<p>This is a <strong>test email</strong>.</p>
<p>If you see this, email configuration is working! ✅</p>
<hr>
<small>Generated by test_email.py</small>
</body></html>
"""

msg.attach(MIMEText(text, 'plain', 'utf-8'))
msg.attach(MIMEText(html, 'html', 'utf-8'))

# Send
try:
    print("📧 Connecting to Gmail SMTP...")
    server = smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT)
    server.login(USER, PASS)
    print("🔐 Logged in successfully")
    server.sendmail(FROM, TO, msg.as_string())
    print("✅ Email sent successfully to:", ', '.join(TO))
    server.quit()
except Exception as e:
    print(f"❌ Failed: {type(e).__name__}: {e}")
